// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.analytics.purview.share;

import com.azure.core.util.ServiceVersion;

/** Service version of PurviewShareClient. */
public enum PurviewShareServiceVersion implements ServiceVersion {
    /** Enum value 2022-06-30-preview. */
    V2022_06_30_PREVIEW("2022-06-30-preview");

    private final String version;

    PurviewShareServiceVersion(String version) {
        this.version = version;
    }

    /** {@inheritDoc} */
    @Override
    public String getVersion() {
        return this.version;
    }

    /**
     * Gets the latest service version supported by this client library.
     *
     * @return The latest {@link PurviewShareServiceVersion}.
     */
    public static PurviewShareServiceVersion getLatest() {
        return V2022_06_30_PREVIEW;
    }
}
